- type: latheRecipe
  id: MedicalScannerMachineCircuitboardSoyuz
  result: MedicalScannerMachineCircuitboard
  completetime: 5
  materials:
    Steel: 500
    Glass: 500
    Gold: 500
    Silver: 500
    Plastic: 500
    Plasma: 500
    Uranium: 500

- type: latheRecipe
  id: CloningConsoleComputerCircuitboardSoyuz
  result: CloningConsoleComputerCircuitboard
  completetime: 5
  materials:
    Steel: 500
    Glass: 500
    Gold: 500
    Silver: 500
    Plastic: 500
    Plasma: 500
    Uranium: 500

- type: latheRecipe
  id: ExperimentalCloningPodMachineCircuitboard
  result: ExperimentalCloningPodMachineCircuitboard
  completetime: 5
  materials:
    Steel: 500
    Glass: 500
    Gold: 500
    Silver: 500
    Plastic: 500
    Plasma: 500
    Uranium: 500