- type: entity
  id: BaseStationTaipanCargo
  abstract: true
  components:
  - type: StationBankAccount
    primaryAccount: Taipan
  - type: StationCargoOrderDatabase
    orders:
      Taipan: [ ]
  - type: StationCargoBountyDatabase
    isTaipan: true

#- type: entity
#  id: BaseTaipanStationJobsSpawning
#  abstract: true
#  components:
#  - type: StationJobs
#    availableJobs: {}
#  - type: StationSpawning

- type: entity
  id: BaseTaipanStationShuttles
  abstract: true
  components:
    - type: GridSpawn
      groups:
        ruins: !type:GridSpawnGroup
          hide: true
          nameGrid: true
          minCount: 1
          maxCount: 1
          minimumDistance: 250
          maximumDistance: 500
          stationGrid: false
          paths:
          - /Maps/Ruins/Taipan/bluespace_science_grid.yml
          - /Maps/Ruins/Taipan/colossal_asteroid.yml
          - /Maps/Ruins/Taipan/lincore_crush.yml

- type: entity
  id: BaseTaipanStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: taipanStationAlerts

- type: entity
  id: BaseStationSiliconTaipanStatic
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: TaipanStatic
